# Generated by Django 4.0.4 on 2022-05-05 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=500)),
                ('deadline', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('tasks', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_members_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects.assigned_members_id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
