# Generated by Django 4.0.4 on 2022-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projects_assigned_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='This is a test title', max_length=100),
            preserve_default=False,
        ),
    ]
