# Generated by Django 4.0.4 on 2022-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
