# Generated by Django 4.0.4 on 2022-05-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='selectedProjectId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedProjectId+', to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks.author+', to=settings.AUTH_USER_MODEL),
        ),
    ]
