# Generated by Django 4.0.4 on 2022-05-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_tasks_selectedprojectid_alter_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tasks',
        ),
    ]
