# Generated by Django 4.0.4 on 2022-05-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_tasks_selectedprojectid_tasks_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='comments',
        ),
    ]
