# Generated by Django 4.0.4 on 2022-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=500)),
                ('deadline', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('assigned_members', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('tasks', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
